# Dockerizing MongoDB: Dockerfile for building MongoDB images
# Based on ubuntu:latest, installs MongoDB following the instructions from:
# http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

# Format: FROM    repository[:version]
FROM       ubuntu:latest

# Format: MAINTAINER Name <email@addr.ess>
MAINTAINER Kaloz <krisztian.lachata@gmail.com>

#Generator modifies this for the final user
ENV USER DOCKER_FOR

#Installation: tools
RUN apt-get update && apt-get install -y git curl

#Add new user
RUN useradd -m $USER && chpasswd $USER:'pwd123' && \
    echo "$USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p /home/$USER/.ssh && \
    ssh-keyscan github.com >> /home/$USER/.ssh/known_hosts && \
    chown -R $USER:$USER /home/$USER

COPY logo.txt /home/$USER
COPY .bashrc /home/$USER
COPY id_rsa /home/$USER/.ssh

# Clone the conf files into the docker container
#RUN sshpass -p 'n0xyt4' git clone git@github.com:lachatak/gatling-cometd.git

USER lachatak
WORKDIR /home/lachatak

# Define default command.
CMD ["bash"]
