# Dockerizing Developer environment

# Format: FROM    repository[:version]
FROM       ubuntu:latest

# Format: MAINTAINER Name <email@addr.ess>
MAINTAINER Kaloz <krisztian.lachata@gmail.com>

#Generator modifies this for the final user
ENV USER DOCKER_FOR
ENV HOME /home/DOCKER_FOR

#Installation: tools
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget && \
  rm -rf /var/lib/apt/lists/*

#Add new user
RUN useradd -m DOCKER_FOR -u 1000 -G sudo -s /bin/bash && \
    echo $USER':pwd123' | chpasswd && \
    echo "%sudo	ALL=(ALL:ALL) ALL" >> /etc/sudoers && \
    mkdir -p /home/$USER/.ssh && \
    ssh-keyscan github.com >> /home/$USER/.ssh/known_hosts && \
    chown -R $USER:$USER /home/$USER

COPY user/logo.txt /home/$USER/
COPY user/.bashrc /home/$USER/

#Injected services go here
SERVICES

VOLUME ["/home/DOCKER_FOR/Documents/workspaces", "/home/DOCKER_FOR/.ssh/id_rsa"]
WORKDIR /home/DOCKER_FOR
USER DOCKER_FOR

#IDE

# Define default command.
CMD ["bash"]
